### ISSUE TITLE
May HEAD set content-type and content-length?

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#110]
From upload-length and possibly upload-type?

**Comment by Acconut** [comment]
> content-type

I dislike the idea of adding the `Upload-Type` header for the reason I pointed out at https://github.com/tus/tus-resumable-upload-protocol/issues/103#issuecomment-262205697. However, the specification does not prohibit that one adds the `Content-Type` header to the response. If you want so, you may pull the value from the upload's metadata or detect it checking the file for magic numbers.

> content-length

If you want to add this header you have to watch out! Its value must be the length of the response body which will be available if you send a GET request to the same URL. This means that 1) if your server does not allow GET requests, you must not set this header and 2) if this upload is not finished, it should rather be the upload's current offset instead of its length.

**Comment by ronag** [comment]
> 2) if this upload is not finished, it should rather be the upload's current offset instead of its length.

But is this really true if the server (like ours) supports streaming a growing file?

**Comment by Acconut** [comment]
> But is this really true if the server (like ours) supports streaming a growing file?

This absolutely depends on what the server offers if you hit it with a GET request. If you stream the entire file while it's uploading, you may use the upload's length as you said. If you only offer the incomplete upload, it should be the offset.
