### ISSUE TITLE
Support streams with unknown length?

### ISSUE THREAD

**Issue by felixge** [tus/tus-resumable-upload-protocol#16]
see discussion here: http://www.tus.io/protocols/resumable-upload.html#comment-865108402

**Comment by Acconut** [comment]
See #49 for the proposed changes.

**Comment by qsorix** [comment]
A new round of questions :)

Let's say a client started to upload an infinite stream, e.g. live video recording.

What should happen when at some point server decides it cannot accept more data?
It could close the reading half-connection and send back an error code but I don't know if it follows HTTP framework. Some client libraries may have difficulties handling that. The other option is to simply close both ends of the connection. Then what should happen on subsequent HEAD requests on that resource? Should the server kill (i.e. remove) the upload? Can the client decide that since it cannot send anything more, it is OK to finish here and send an empty PATCH with `Entity-Length` equal to the current `Offset`?

Another one:

Can a streaming upload be used to provide stream oriented processing or should this be beyond the scope? In other words, can server start processing the incoming data while the upload is still unfinished? This can potentially save a lot of server's disk space and spread resource utilization over time. Should implementations be allowed to do this or can you think of any problems? I think it prevents checking the control sum but implementation may not care.

**Comment by Acconut** [comment]
> What should happen when at some point server decides it cannot accept more data?
It could close the reading half-connection and send back an error code but I don't know if it follows HTTP framework. Some client libraries may have difficulties handling that. The other option is to simply close both ends of the connection. Then what should happen on subsequent HEAD requests on that resource? Should the server kill (i.e. remove) the upload?

As long as the server hasn't sent any status code yet (or responded with a `100 Continue`) it can send a `503 Service Unavailable` else the only solution is to close the connection and wait until the client retries. This behaviour is defined in the retries extension. If the server removed the upload (recommended if it won't accept more input in the future) it should return with a `404 Not Found` to HEAD and PATCH requests.

> Can the client decide that since it cannot send anything more, it is OK to finish here and send an empty PATCH with Entity-Length equal to the current Offset?

It depends on the client's usage. If the resource is still available but can't be completed the client may do so.

> Can a streaming upload be used to provide stream oriented processing or should this be beyond the scope? In other words, can server start processing the incoming data while the upload is still unfinished? This can potentially save a lot of server's disk space and spread resource utilization over time. Should implementations be allowed to do this or can you think of any problems? I think it prevents checking the control sum but implementation may not care.

In theory yes, but the protocols also allows offsets different then the current amount of uploaded bytes (see non-contiguous chunks and parallel uploads). So you can't rely on this currently since
the protocol says that the offset may be smaller (I disagree on this by the way). That's also a problem when looking at streaming downloads (see #28).

**Comment by Acconut** [comment]
Implement in #49.
