### ISSUE TITLE
Describe large file chunking as a part of protocol

### ISSUE THREAD

**Issue by wronglink** [tus/tus-resumable-upload-protocol#24]
Many frameworks and webservers have predefined request maximum size. Hanlding a huge file upload in one request is not trivial task. The current version of protocol says:

> Clients SHOULD send all remaining bytes of a resource in a single PATCH request, but MAY also use multiple small requests for scenarios where this is desirable (e.g. NGINX buffering requests before they reach their backend).

But how can client know what is the maximum size of 1 chunk? In most cases if client tries to send too big request the server would return a 413 error or something like this and client would not know what to do now.

I think that an additional header (lets say `Max-Content-Length`) that server returns on initial POST and HEAD requests can help us with that.

I haven't found any existing headers for such task so I suggest to use a custom one. Here is a small example (we want to send 50 mb file):

**Request:**

```
POST /files HTTP/1.1
Host: tus.example.org
Content-Length: 0
Final-Length: 52428800
```

**Response:**

```
HTTP/1.1 201 Created
Max-Content-Length: 10485760
Location: http://tus.example.org/files/24e533e02ec3bc40c387f1a0e460e216
```

Ok. Now client knows that only 10 mb per request is allowed. Than it sends chunks. If something went wrong - make `HEAD` request, detect the offset and continue.

**Comment by g-bull** [comment]
I am faced with this exact issue and like the Max-Content-Length proposal by wronglink.
That didn't get up because "The current way we plan to approach your issue is by adding the discovery mechanism as discussed in #29" - but I think that plan never came to fruition right?
Since I have control of the client and server, I am going with the Max-Content-Length proposal unless someone tells me a better way actually exists.

**Comment by Acconut** [comment]
@g-bull It sounds as if you are looking for the proposal as in https://github.com/tus/tus-resumable-upload-protocol/pull/93. Did you have a look at that?
